recover:
   application:
      list : alipay-service,wechat-service,pay-service
   serializer :
      support: kryo
   retry :
      max: 10
   redis:
      cluster: false
    # clusterUrl : 127.0.0.1:70001;127.0.1:7002
      hostName : 127.0.0.1
      port : 6379
      password :
