server:
  port: 8882
  contextPath: /alipay-service
  address: 0.0.0.0


spring:
    datasource:
        driver-class-name:  com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/alipay?useUnicode=true&characterEncoding=utf8
        username: root
        password: root
    application:
      name: alipay-service

mybatis:
  type-aliases-package: com.raincat.springcloud.sample.alipay.entiy
#${random.int[9000,9999]}
eureka:
 client:
     serviceUrl:
       defaultZone: http://localhost:8761/eureka/

alipay-service :
   ribbon.NFLoadBalancerRuleClassName : com.netflix.loadbalancer.RandomRule

logging:
  level:
      root: info
      com.raincat.core : debug
  path: "./logs"

